version: '3.9'

x-common: &default
  build: .
  volumes:
    - .:/code
  env_file:
    - .env

services:
  web:
    <<: *default
    command: gunicorn AIRBNB.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7

  celery_worker:
    <<: *default
    command: celery -A AIRBNB worker -l info
    depends_on:
      - db
      - redis

  celery_beat:
    <<: *default
    command: celery -A AIRBNB beat -l info
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
