version: "3.9"

services:
  web:
    build: .
    container_name: airbnb_web
    command: gunicorn AIRBNB.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - ./media:/app/media
      - ./static:/app/static
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: airbnb_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
      
  redis:
    image: redis:7
    container_name: airbnb_redis
    restart: always
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    container_name: airbnb_celery_worker
    command: celery -A AIRBNB worker -l info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

  celery_beat:
    build: .
    container_name: airbnb_celery_beat
    command: celery -A AIRBNB beat -l info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:latest
    container_name: airbnb_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./media:/app/media
      - ./static:/app/static
    depends_on:
      - web

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge